# Update src/main/resources/plugin.yml (add borax command, update combat desc)
name: PlayerLocs
version: '${version}'
main: com.example.PlayerLocs
api-version: '1.21'
author: You
commands:
  loc:
    description: Get specific player location.
    usage: /loc <player/uuid>
    permission: playerlocs.use
  fight:
    description: Manage Fight mode teams and start fights
    usage: /fight <team1|team2|start|end|clear|scores|status|reload|toggle|list>
    permission: fight.use
  combat:
    description: Lookup/delete combat data
    usage: /combat lookup <player-or-uuid>
    permission: combat.use
  borax:
    description: Plugin help
    usage: /borax help
    permission: borax.use
  inventory:
    description: View player inventory (online/offline)
    usage: /inventory <player|uuid|all> [world=world]
    permission: inventory.use
  escrow:
    description: Manage combat log escrow
    usage: /escrow <player> <release|list>
    permission: mcraft.escrow
permissions:
  playerlocs.use:
    default: op
  fight.use:
    default: op
  combat.use:
    default: op
  borax.use:
    default: true  # Open to all
  inventory.use:
    default: op
  mcraft.escrow:
    default: op