# Update src/main/resources/plugin.yml (add delete to combat command)
name: PlayerLocs
version: '${project.version}'
main: com.example.PlayerLocs
api-version: '1.21'
author: You
commands:
  locs:
    description: Send player locations to API
    usage: /locs
    permission: playerlocs.use
  fight:
    description: Manage Fight mode teams and start fights (list open to all)
    usage: /fight <team1|team2|start|end|clear|scores|status|reload|toggle|list>
    permission: fight.use
  combat:
    description: Lookup/delete combat data
    usage: /combat <lookup> <player-or-uuid> [recent|full] [limit] | /combat <delete> <player-or-uuid|all> <timespan e.g. 5d>
    permission: combat.use
permissions:
  playerlocs.use:
    description: Use /locs
    default: op
  fight.use:
    description: Use Fight mode (except list)
    default: op
  combat.use:
    description: Use combat lookup/delete
    default: op